version: "3"

networks:
  loki:
    name: loki
  nginx-proxy:
    name: nginx-proxy

services:
  loki:
    image: grafana/loki:2.7.3
    ports:
      - "3100:3100"
    environment:
      VIRTUAL_HOST: ${DOCKER_ENV_LOKI_HOST}
      VIRTUAL_PORT: 3100
      LETSENCRYPT_HOST: ${DOCKER_ENV_LOKI_HOST}
      LETSENCRYPT_EMAIL: ${DOCKER_ENV_EMAIL}
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
      - nginx-proxy

  grafana:
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      VIRTUAL_HOST: ${DOCKER_ENV_GRAFANA_HOST}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${DOCKER_ENV_GRAFANA_HOST}
      LETSENCRYPT_EMAIL: ${DOCKER_ENV_EMAIL}
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
      - nginx-proxy
